pipeline {
  agent {
    docker { image 'python:3.10-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'python --version'
      }
    }
    stage('Setup Python Environment'){
      steps{
        sh '''
        python -m venv venv
        source venv/bin/activate
        python --version
        '''
      }
    }
    stage('Install Dependencies'){
      steps{
        sh '''
        source venv/bin/activate
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        '''
      }
    }
  }
}
