pipeline {
  agent {
    docker { image 'python:3.10-alpine' }
  }
  environment {
    CI = 'true'  // Enable CI mode
    PYTEST_ARGS = "tests/ --junitxml=reports/test-results.xml -v -s"
  }
  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/sdutta24/devops-pipeline-test', branch: 'main'
      }
    }
    stage('Setup Python Environment'){
      steps{
        sh '''
        python -m venv venv
        source venv/bin/activate
        python --version
        '''
      }
    }
    stage('Install Dependencies'){
      steps{
        sh '''
        source venv/bin/activate
        pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        '''
      }
    }
    stage('Run Calculator Script') {
      steps {
        sh '''
        source venv/bin/activate
        cd $WORKSPACE/my-first-job
        python calculator1.py
        '''
      }
    }
    stage('Run Tests') {
    steps {
        sh '''
        source venv/bin/activate
        export PYTHONPATH=$WORKSPACE/my-first-job
        cd $WORKSPACE/my-first-job
        pytest $PYTEST_ARGS
        '''
    }
   }
  }
}
