pipeline {
  agent {
    docker { image 'python:3.10-alpine' }
  }
  environment {
    CI = 'true'  // Enable CI mode
  }
  stages {
    stage('Checkout') {
      steps {
        git url: 'https://github.com/sdutta24/devops-pipeline-test', branch: 'main'
      }
    }
    stage('Setup Python Environment'){
      steps{
        sh '''
        python -m venv venv
        source venv/bin/activate
        python --version
        '''
      }
    }
    stage('Install Dependencies'){
      steps{
        sh '''
        source venv/bin/activate
        pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        '''
      }
    }
  }
}
